language: node_js
node_js:
  - "node"
  - "7"
  - "6"
os:
  - linux
  - osx
branches:
  except: 
    - develop
before_install:
after_success:
after_failure:
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f596466e5c30701b566d
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
