clone_depth: 1
environment:
  matrix:
    - nodejs_version: '6'
    - nodejs_version: '7'
install:
  - ps: 'Install-Product node $env:nodejs_version'
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install
build: 'off'
test_script:
  - node --version && npm --version
  - npm test
version: 2.0.0-alpha.13
